FROM python:3.8-slim

# 환경 변수 설정
ENV FIREBASE_API_KEY=${FIREBASE_API_KEY} \
    FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN} \
    FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID} \
    FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET} \
    FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID} \
    FIREBASE_APP_ID=${FIREBASE_APP_ID} \
    ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY} \
    OPENAI_API_KEY=${OPENAI_API_KEY} \
    PRIVATE_KEY_ID=${PRIVATE_KEY_ID} \
    PRIVATE_KEY=${PRIVATE_KEY} \
    CLIENT_EMAIL=${CLIENT_EMAIL} \
    CLIENT_ID=${CLIENT_ID} \
    CLIENT_X509_CERT_URL=${CLIENT_X509_CERT_URL} \
    GITHUB_TOKEN=${GITHUB_TOKEN}

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

CMD ["python", "server.py"]
