name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: secrets
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and push Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_USERNAME }}/contralysis . 
        sudo docker stop $(sudo docker ps -q) 2>/dev/null || true
        docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/contralysis
