name: Python package

on: [push]

jobs:

  unit-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
          
      - name: Test with pytest
        id: pytest
        run: pytest
        continue-on-error: true

      # - name: Create issue on failure
      #   if: ${{ steps.pytest.outcome == 'failure' }}
      #   uses: JasonEtco/create-an-issue@v2
      #   with:
      #     title: "Test Failure: ${{ github.sha }}"
      #     body: |
      #       One or more tests failed in the build. Please check the workflow run for details:
      #       ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      #     labels: bug
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ISSUE_TOKEN }}

      - name: Create GitHub Issue on Failure
        if: failure() && ${{ steps.pytest.outcome == 'failure' }}
        env:
          GITHUB_TOKEN: ${{ secrets.ISSUE_TOKEN }}
        run: |
          gh issue create —t "Automated Test Failure" —b "The 'Test with pytest' step has failed. Please investigate the issue." —l "bug"
        shell: bash
        continue-on-error: false
